spring:
  application:
    name: microservice02
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      username: theUser
      password: fooPass10Bar!
  boot:
    admin:
      client:
        url: http://localhost:8000