server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice01
          uri: lb://microservice01
          predicates:
            - Path=/resourceA
        - id: microservice02
          uri: lb://microservice02
          predicates:
            - Path=/resourceB
        - id: microservice03
          uri: lb://microservice03
          predicates:
            - Path=/resourceC
