global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "microservicesTemplate"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "mocroservice01"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "mocroservice02"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: "mocroservice03"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8083"]
# rule_files:
#   - "/etc/prometheus/alertmanager/rules.yml"

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets:
#             - "alertmanager:9093"
